# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mercury' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Unbox', '~> 2.5.0'
  pod 'Alamofire', '~> 4.7.0'
  pod 'KeychainAccess', '~> 3.1.0'

  target 'MercuryTests' do
    inherit! :search_paths
    
    pod 'Quick'
    pod 'Nimble'
  end

end
